import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Download,
  Upload,
  FileJson,
  Globe,
  Package,
  Share2,
  Copy,
  Check,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import type { Dashboard, WidgetConfig, WidgetLayout } from "@shared/schema";

interface DashboardExportProps {
  dashboard: Dashboard;
  widgets: WidgetConfig[];
  layout: WidgetLayout[];
}

type ExportFormat = "json" | "html" | "zip" | "url";

export function DashboardExport({ dashboard, widgets, layout }: DashboardExportProps) {
  const [exportFormat, setExportFormat] = useState<ExportFormat>("json");
  const [exportName, setExportName] = useState(dashboard.name || "dashboard");
  const [shareUrl, setShareUrl] = useState("");
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const generateExportData = () => {
    const exportData = {
      version: "2.0.0",
      metadata: {
        name: exportName,
        description: `Exported dashboard from µCodeLab`,
        created: new Date().toISOString(),
        author: "µCodeLab User",
        version: "1.0.0"
      },
      dashboard: {
        ...dashboard,
        widgets,
        layout
      }
    };

    return exportData;
  };

  const exportAsJSON = () => {
    const data = generateExportData();
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${exportName}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({ title: "Exported", description: "Dashboard exported as JSON file." });
  };

  const exportAsHTML = () => {
    const data = generateExportData();
    
    const htmlTemplate = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${exportName} - µCodeLab Dashboard</title>
    <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { font-family: Inter, system-ui, sans-serif; }
        .dashboard-container { 
            max-width: 1200px; 
            margin: 0 auto; 
            padding: 20px; 
        }
        .widget { 
            background: white; 
            border: 1px solid #e5e7eb; 
            border-radius: 8px; 
            padding: 16px; 
            margin: 8px; 
        }
    </style>
</head>
<body class="bg-gray-50">
    <div class="dashboard-container">
        <header class="mb-8">
            <h1 class="text-3xl font-bold text-gray-900">${exportName}</h1>
            <p class="text-gray-600">Exported from µCodeLab v2.0</p>
        </header>
        
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            ${widgets.map(widget => `
                <div class="widget">
                    <h3 class="font-semibold mb-2">${widget.label}</h3>
                    <p class="text-sm text-gray-600">Type: ${widget.type}</p>
                    ${widget.variableName ? `<p class="text-sm text-gray-600">Variable: ${widget.variableName}</p>` : ''}
                    ${widget.unit ? `<p class="text-sm text-gray-600">Unit: ${widget.unit}</p>` : ''}
                </div>
            `).join('')}
        </div>
        
        <footer class="mt-8 pt-4 border-t text-center text-sm text-gray-500">
            <p>Generated by µCodeLab v2.0 - IoT Dashboard Builder</p>
            <p>Dashboard Data: <code>${JSON.stringify(data).length} bytes</code></p>
        </footer>
    </div>
    
    <script>
        // Dashboard data embedded for future interactive features
        window.dashboardData = ${JSON.stringify(data)};
        console.log('Dashboard data loaded:', window.dashboardData);
    </script>
</body>
</html>`;

    const blob = new Blob([htmlTemplate], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${exportName}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({ title: "Exported", description: "Dashboard exported as standalone HTML file." });
  };

  const exportAsZIP = async () => {
    // For a real implementation, you'd use a library like JSZip
    toast({ 
      title: "Coming Soon", 
      description: "ZIP export with assets will be available in a future update.",
      variant: "default"
    });
  };

  const generateShareUrl = () => {
    const data = generateExportData();
    const compressed = btoa(JSON.stringify(data));
    const url = `${window.location.origin}/dashboard/shared?data=${compressed}`;
    setShareUrl(url);
    
    toast({ title: "Share URL Generated", description: "Dashboard can now be shared via URL." });
  };

  const copyShareUrl = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast({ title: "Copied", description: "Share URL copied to clipboard." });
    } catch (err) {
      toast({ 
        title: "Copy Failed", 
        description: "Could not copy to clipboard. Please copy manually.",
        variant: "destructive"
      });
    }
  };

  const handleExport = () => {
    switch (exportFormat) {
      case "json":
        exportAsJSON();
        break;
      case "html":
        exportAsHTML();
        break;
      case "zip":
        exportAsZIP();
        break;
      case "url":
        generateShareUrl();
        break;
    }
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Share2 className="h-4 w-4" />
          Export
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Download className="h-5 w-5" />
            Export Dashboard
          </DialogTitle>
          <DialogDescription>
            Export your dashboard in various formats for sharing or backup
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Export Settings */}
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Export Name</Label>
              <Input
                value={exportName}
                onChange={(e) => setExportName(e.target.value)}
                placeholder="My Dashboard"
              />
            </div>

            <div className="space-y-2">
              <Label>Export Format</Label>
              <Select value={exportFormat} onValueChange={(value: ExportFormat) => setExportFormat(value)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="json">
                    <div className="flex items-center gap-2">
                      <FileJson className="h-4 w-4" />
                      JSON Configuration
                    </div>
                  </SelectItem>
                  <SelectItem value="html">
                    <div className="flex items-center gap-2">
                      <Globe className="h-4 w-4" />
                      Standalone HTML
                    </div>
                  </SelectItem>
                  <SelectItem value="zip">
                    <div className="flex items-center gap-2">
                      <Package className="h-4 w-4" />
                      ZIP Archive (Coming Soon)
                    </div>
                  </SelectItem>
                  <SelectItem value="url">
                    <div className="flex items-center gap-2">
                      <Share2 className="h-4 w-4" />
                      Shareable URL
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Format Descriptions */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Format Details</CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              {exportFormat === "json" && (
                <div>
                  <p className="font-medium mb-2">JSON Configuration File</p>
                  <ul className="space-y-1 list-disc list-inside">
                    <li>Complete dashboard configuration</li>
                    <li>Can be imported into other µCodeLab instances</li>
                    <li>Includes all widget settings and layout</li>
                    <li>Human-readable format</li>
                  </ul>
                </div>
              )}
              
              {exportFormat === "html" && (
                <div>
                  <p className="font-medium mb-2">Standalone HTML File</p>
                  <ul className="space-y-1 list-disc list-inside">
                    <li>Self-contained HTML file</li>
                    <li>Opens in any web browser</li>
                    <li>Static preview of dashboard layout</li>
                    <li>Includes embedded dashboard data</li>
                  </ul>
                </div>
              )}
              
              {exportFormat === "zip" && (
                <div>
                  <p className="font-medium mb-2">ZIP Archive (Coming Soon)</p>
                  <ul className="space-y-1 list-disc list-inside">
                    <li>Complete dashboard package</li>
                    <li>Includes all assets and dependencies</li>
                    <li>Ready for deployment</li>
                    <li>Documentation included</li>
                  </ul>
                </div>
              )}
              
              {exportFormat === "url" && (
                <div>
                  <p className="font-medium mb-2">Shareable URL</p>
                  <ul className="space-y-1 list-disc list-inside">
                    <li>Dashboard encoded in URL parameters</li>
                    <li>Share via link, email, or QR code</li>
                    <li>No file download required</li>
                    <li>Instant preview for recipients</li>
                  </ul>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Share URL Result */}
          {exportFormat === "url" && shareUrl && (
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base">Share URL</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <Textarea
                  value={shareUrl}
                  readOnly
                  rows={3}
                  className="font-mono text-sm"
                />
                <Button
                  onClick={copyShareUrl}
                  className="w-full"
                  variant="outline"
                >
                  {copied ? (
                    <>
                      <Check className="h-4 w-4 mr-2" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="h-4 w-4 mr-2" />
                      Copy URL
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          )}

          {/* Export Stats */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Export Summary</CardTitle>
            </CardHeader>
            <CardContent className="text-sm">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-muted-foreground">Widgets</p>
                  <p className="font-semibold">{widgets.length}</p>
                </div>
                <div>
                  <p className="text-muted-foreground">Layout Items</p>
                  <p className="font-semibold">{layout.length}</p>
                </div>
                <div>
                  <p className="text-muted-foreground">Data Size</p>
                  <p className="font-semibold">{Math.round(JSON.stringify(generateExportData()).length / 1024)} KB</p>
                </div>
                <div>
                  <p className="text-muted-foreground">Version</p>
                  <p className="font-semibold">2.0.0</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Export Button */}
          <Button onClick={handleExport} className="w-full" size="lg">
            <Download className="h-4 w-4 mr-2" />
            {exportFormat === "url" ? "Generate Share URL" : `Export as ${exportFormat.toUpperCase()}`}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}